version: "3.5"
services:
  feuer:
    build: .
    image: "feuer_${ENVIRONMENT}"
    ports:
      - "6000:6000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feuer_${ENVIRONMENT}.rule=Host(${HOST})"
      - "traefik.http.routers.feuer_${ENVIRONMENT}.entrypoints=websecure"
      - "traefik.http.routers.feuer_${ENVIRONMENT}.tls.certresolver=letsencrypt"
    networks:
      - jnet

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$FEUER_DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$FEUER_DB_PASSWORD
    volumes:
      - db:/data/db
    networks:
      - jnet
networks:
  jnet:
    name: jnet

volumes:
  db:
