export enum Sprite {
  envTreeSmall= 0,
  envTreeBig,
  envTreeFirSmall,
  envTreeFirBig,
  envTreeFullFirSmall,
  envTreeFullFirBig,
  envTreeFirSnow,
  envCactus1,
  envCactus2,
  envRock01,
  envRock02,
  envRock04,
  envRock05,
  envIron,
  envGold,
}

export const 
  level_water_deep:number = 0.05,
  level_water_shallow:number = 0.1,
  level_sand:number = 0.15,
  level_sand_grassy:number = 0.2,
  level_grass_sandy:number = 0.25,
  level_grass:number = 0.6,
  level_grass_dirty:number = 0.65,
  level_dirt_grassy:number = 0.7,
  level_dirt:number = 0.7,
  level_dirt_stony:number = 0.75,
  level_stone_dirty:number = 0.8,
  level_stone:number = 0.9,
  level_ice:number = 1;